version: "3.9"

services:
  coredns:
    image: coredns/coredns:1.9.4
    restart: unless-stopped
    command: -conf /etc/Corefile
    networks:
      default:
        ipv4_address: 172.31.1.1
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - ./Corefile:/etc/Corefile:ro

  proxy:
    image: nginx:1.21
    depends_on:
      - coredns
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../../certs:/etc/nginx/certs

networks:
  default:
    name: development
    ipam:
      config:
        - subnet: 172.31.0.0/16
