version: "3.7"

services:
  asynqmon:
    image: hibiken/asynqmon:0.6.0
    environment:
      PORT: "8080"
      REDIS_ADDR: "host.docker.internal:6379"
    ports:
      - "8888:8080"

networks:
  default:
    name: happydevel
    external: true
